import { z } from "zod";

export const PapelSistemaSchema = z.enum(["ADMIN", "USUARIO"]);

export type PapelSistema = z.infer<typeof PapelSistemaSchema>;

export enum Permissoes {
	'CONFIGURAR_EMPRESA' = 'CONFIGURAR_EMPRESA',
	'CADASTRAR_USUARIOS' = 'CADASTRAR_USUARIOS',
	'CADASTRAR_EQUIPES' = 'CADASTRAR_EQUIPES',
	'VER_TODAS_VENDAS' = 'VER_TODAS_VENDAS',
	'VER_TODAS_EQUIPES' = 'VER_TODAS_EQUIPES',
	'AUDITAR_VENDA' = 'AUDITAR_VENDA',
	'ALTERAR_VENDEDOR' = 'ALTERAR_VENDEDOR',
	'REALIZAR_AUTOMACOES' = 'REALIZAR_AUTOMACOES',
	'VER_LIXEIRA' = 'VER_LIXEIRA',
}